# config/config.yaml
server:
  host: "0.0.0.0"
  port: 8002
  websocket_path: "/ws"
  max_connections: 1000

camera:
  poll_interval: 0.1          # seconds
  detection_timeout: 2.0      # seconds  
  devices_range: [0, 9]       # /dev/video0 to /dev/video9
  default_resolution: "640x480"
  default_fps: 30
  capability_timeout: 2.0     # seconds for v4l2-ctl commands

logging:
  level: "INFO"
  log_dir: "/opt/webcam-env/logs"
  file_enabled: true
  max_file_size: "10MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

performance:
  use_uvloop: true           # Linux only
  connection_timeout: 30.0   # seconds
  ping_timeout: 5.0         # seconds

security:
  allowed_origins: ["*"]     # WebSocket CORS origins
  rate_limit_enabled: false
  max_requests_per_minute: 60